detectors:
  cpu1:
    type: cpu
mqtt:
  host: 192.168.2.121
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: USERNAME
  password: PASSWORD
  stats_interval: 60

cameras:
  Front_Garden:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
        rtmp: preset-rtmp-ubiquiti
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://192.168.1.33:7447/No4QZgibW4ZvrGUw
          roles:
            - detect
        - path: rtsp://192.168.1.33:7447/gQWwE4xi7A200gkE
          roles:
            - record

    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - car
        - person
        - dog


  Rear_Garden:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.33:7447/GAricjgQHMsscTdP
          roles:
            - detect
    detect:
      enabled: False
      width: 1280
      height: 720

  Drive:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.33:7447/ZYUqESurTceKPw9T
          roles:
            - detect
    detect:
      enabled: False
      width: 1280
      height: 720

  Annke:
    ffmpeg:
      inputs:
        - path: rtsp://USERNAME:PASSWORD@192.168.1.140:554/Streaming/Channels/2/
          roles:
            - detect
            - record
    detect:
      enabled: true 
      width: 640 
      height: 480 
    objects:
      track:
        - dog
        - cat


  Front_door:
    ffmpeg:
      output_args:
        record: preset-record-ubiquiti
        rtmp: preset-rtmp-ubiquiti
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsps://192.168.1.33:7441/SCN2xU87lWz9Lh5V?enableSrtp
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1024
      height: 576
    objects:
      track:
        - person

record:
  enabled: True
  events:
    retain:
      default: 2
    pre_capture: 5
    post_capture: 5
snapshots:
  enabled: True
