---
- hosts: all
  become: yes
  tasks:
    - name: Install Packges
      apt:
          name: "{{ item }}"
          state: latest
      with_items:
          - ntp
          - vim
          - locate
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

     - name: Install Packges Ubuntu
       apt:
           name: "{{ item }}"
           state: latest
       with_items:
           - nfs-common
       when: ansible_distribution == "Ubuntu"

