---
- hosts: 192.168.2.32
  become: yes
  tasks:
    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 192.168.1.191:/mnt/HD/HD_a2/Pi_backups
        path: /mnt/backup
        opts: rw,sync,hard
        state: mounted
        fstype: nfs
