---
- hosts: all
  become: yes
  tasks:
    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 192.168.30.54:/pi_backups
        path: /mnt/backup/Pi_Backups
        opts: auto,_netdev,nofail,x-systemd.automount
        state: mounted
        fstype: nfs
